live_config_reload: true

window:
  opacity: 0.90
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: none

font:
  normal:
    family: "JetBrainsMonoNL Nerd Font"
    style: Regular
  size: 13.0

\n\nshell:\n program: /bin/zsh\n args:\n - --login\n
shell:
  program: /bin/zsh
  args:
    - --login

colors:
  primary:
    background: "#191a1c"
    foreground: "#e6eaea"
    dim_foreground: "#cbd9d8"
    bright_foreground: "#eaeeee"
  cursor:
    text: "#e6eaea"
    cursor: "#cbd9d8"
  vi_mode_cursor:
    text: "#e6eaea"
    cursor: "#a1cdd8"
  search:
    matches:
      foreground: "#e6eaea"
      background: "#425e5e"
    focused_match:
      foreground: "#e6eaea"
      background: "#7aa4a1"
  footer_bar:
    foreground: "#e6eaea"
    background: "#254147"
  hints:
    start:
      foreground: "#e6eaea"
      background: "#ff8349"
    end:
      foreground: "#e6eaea"
      background: "#254147"
  selection:
    text: "#e6eaea"
    background: "#293e40"
  normal:
    black: "#2f3239"
    red: "#e85c51"
    green: "#7aa4a1"
    yellow: "#fda47f"
    blue: "#5a93aa"
    magenta: "#ad5c7c"
    cyan: "#a1cdd8"
    white: "#ebebeb"
  bright:
    black: "#4e5157"
    red: "#eb746b"
    green: "#8eb2af"
    yellow: "#fdb292"
    blue: "#73a3b7"
    magenta: "#b97490"
    cyan: "#afd4de"
    white: "#eeeeee"
  dim:
    black: "#282a30"
    red: "#c54e45"
    green: "#688b89"
    yellow: "#d78b6c"
    blue: "#4d7d90"
    magenta: "#934e69"
    cyan: "#89aeb8"
    white: "#c8c8c8"
  indexed_colors:
    - index: 16
      color: "#ff8349"
    - index: 17
      color: "#cb7985"
