live_config_reload: true

window:
  opacity: 0.85
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: Full

font:
  normal:
    family: "JetBrainsMonoNL Nerd Font"
    style: Regular
  size: 14.0
